env:
  RESOURCE_GROUP_BRANCH: "main"
  RESOURCE_GROUP_FILE_NAME: "ResourceGroup"

name: Azure Resources Deployment for Dino Smiles

on:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: repo
      
      - name: Install and login to Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.DINO_SMILES_CLIENT_ID }} -p ${{ secrets.DINO_SMILES_SECRET_VALUE }} --tenant ${{ secrets.DINO_SMILES_TENANT_ID }}
            az account set --subscription ${{ secrets.DINO_SMILES_SUBSCRIPTION_ID }}
            az deployment sub create --name Deployment4 --location canadacentral --template-uri \
              https://raw.githubusercontent.com/SN705/Deploy_Resources_in_Azure/${{ env.RESOURCE_GROUP_BRANCH }}/${{ env.RESOURCE_GROUP_FILE_NAME }}.json \
              --parameters https://raw.githubusercontent.com/SN705/Deploy_Resources_in_Azure/main/parameters.json
            az deployment group create --subscription "Dino Smiles" --resource-group "ShowingPresentation" --template-uri \
              https://raw.githubusercontent.com/SN705/Deploy_Resources_in_Azure/main/WebServer.json
