env:
  JSON_FILE_NAME: "ResourceGroup"

name: Azure Resource Group Subscription-Level Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Install and login to Azure
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
            az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            az deployment sub create --name RGAttempt2 --location eastus --template-uri https://raw.githubusercontent.com/SN705/Create_RG_in_Azure/main/${{ env.JSON_FILE_NAME }}.json
            
